import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar/Navbar'
import { Fragment } from 'react'
import Baner from '../components/header/Baner'
import Footer from '../components/footer/Footer'


export default function Home() {
  return (
    <Fragment>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/vercel.svg" />
      </Head>
      <Navbar />
      <Baner/>

    </div>
    <Footer />
    </Fragment>
  )
}
