import React, { Fragment } from "react";
import Footer from "../components/footer/Footer";
import Head from "next/head";
import Profile from "../components/Profile";
import Navbar from "../components/Navbar/Navbar";
import styles from "../styles/Home.module.css";

export default function profile() {
  return (
    <Fragment>
      <div className={`${styles.bg_profile}`}>
        <Head>
          <title>Hirejob</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/vercel.svg" />
        </Head>
        <Navbar />
        <div className={`${styles.bg}`}></div>
        <div></div>
        <Profile />
      </div>
      <Footer />
    </Fragment>
  );
}
